# Generated by Selenium IDE
# pylint: disable=invalid-name,too-many-statements
# pylint: disable=attribute-defined-outside-init
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class TestDiariodeenxaquecaCRUDepisodio():
    def setup_method(self, _):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, _):
        self.driver.quit()

    def test_diariodeenxaquecaCRUDepisodio(self):
        print("=" * 60)
        print("INICIANDO TESTE CRUD DE EPISÓDIOS DE ENXAQUECA")
        print("=" * 60)

        print("\n1. Abrindo página inicial...")
        self.driver.get("http://localhost:3000/")
        self.driver.set_window_size(1678, 1040)
        print("Página inicial carregada")
        time.sleep(3)

        print("\n2. Fazendo login...")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "zenilda.vieira@uol.com.br")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("12345678")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        print("Login realizado")
        time.sleep(3)

        print("\n3. Acessando seção de episódios...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".hover\\3A bg-accent:nth-child(2)").click()
        print("Página de episódios acessada")
        time.sleep(2)

        print("\n4. Iniciando criação de novo episódio...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#6C63FF\\]:nth-child(4)").click()
        print("Formulário de criação de episódio aberto")
        time.sleep(2)

        print("\n5. Selecionando intensidade da dor...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-white:nth-child(2)").click()
        print("Intensidade selecionada")
        time.sleep(1)

        print("\n6. Preenchendo duração...")
        self.driver.find_element(By.CSS_SELECTOR, ".border-primary").click()
        self.driver.find_element(By.ID, "duration").click()
        self.driver.find_element(By.ID, "duration").send_keys("75")
        print("Duração preenchida: 75 minutos")
        time.sleep(1)

        print("\n7. Selecionando gatilhos...")
        self.driver.find_element(By.ID, "trigger-Vinho tinto").click()
        element = self.driver.find_element(By.ID, "trigger-Vinho tinto")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "trigger-Perfume forte").click()
        element = self.driver.find_element(By.ID, "trigger-Perfume forte")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        print("Gatilhos selecionados: Vinho tinto e Perfume forte")
        time.sleep(1)

        print("\n8. Selecionando medicações...")
        self.driver.find_element(By.ID, "medication-Dipirona").click()
        element = self.driver.find_element(By.ID, "medication-Dipirona")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.ID, "medication-Ibuprofeno").click()
        print("Medicações selecionadas: Dipirona e Ibuprofeno")
        time.sleep(1)

        print("\n9. Adicionando notas...")
        self.driver.find_element(By.ID, "notes").click()
        self.driver.find_element(By.ID, "notes").send_keys("amanheci com dor")
        print("Notas adicionadas: 'amanheci com dor'")
        time.sleep(1)

        print("\n10. Salvando episódio...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".hover\\3A bg-\\[\\#5850E6\\]").click()
        print("Episódio salvo")
        time.sleep(2)

        print("\n11. Botão de logout clicado...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".text-\\[\\#E74C3C\\]").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#E74C3C\\]").click()
        time.sleep(2)

        print("\n" + "=" * 60)
        print("TESTE CRUD DE EPISÓDIOS CONCLUÍDO COM SUCESSO")
        print("=" * 60)

