# Generated by Selenium IDE
# pylint: disable=invalid-name,too-many-statements
# pylint: disable=attribute-defined-outside-init
import time

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains


class TestDiariodeenxaquecaCRUDmedicacao():
    def setup_method(self, _):
        self.driver = webdriver.Firefox()
        self.vars = {}
        self.driver.implicitly_wait(10)

    def teardown_method(self, _):
        self.driver.quit()

    def test_diariodeenxaquecaCRUDmedicacao(self):
        print("=" * 60)
        print("INICIANDO TESTE CRUD DE MEDICAÇÕES DE ENXAQUECA")
        print("=" * 60)

        print("\n1. Abrindo página inicial...")
        self.driver.get("http://localhost:3000/")
        self.driver.set_window_size(1453, 1040)
        print("Página inicial carregada")
        time.sleep(3)

        print("\n2. Fazendo login...")
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys(
            "zenilda.vieira@uol.com.br")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("12345678")
        self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
        print("Login realizado")
        time.sleep(3)

        print("\n3. Acessando seção de medicações...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".inline-flex:nth-child(6)").click()
        print("Página de medicações acessada")
        time.sleep(2)

        print("\n4. Iniciando criação de nova medicação...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".hover\\3A bg-\\[\\#5850E6\\]").click()
        print("Formulário de criação de medicação aberto")
        time.sleep(2)

        print("\n5. Preenchendo nome da medicação...")
        self.driver.find_element(By.ID, "medication-name").send_keys(
                "Dipirona Teste")
        print("Nome preenchido: Dipirona Teste")
        time.sleep(1)

        print("\n6. Preenchendo dosagem...")
        self.driver.find_element(By.ID, "medication-dosage").click()
        self.driver.find_element(By.ID, "medication-dosage").send_keys("500mg")
        print("Dosagem preenchida: 500mg")
        time.sleep(1)

        print("\n7. Salvando medicação...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#6C63FF\\]:nth-child(2)").click()
        print("Medicação salva")
        time.sleep(2)

        print("\n8. Editando medicação...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-card:nth-child(6) "
                                 ".inline-flex:nth-child(1)").click()
        self.driver.find_element(By.ID, "medication-name").send_keys(
                "Dipirona Teste para excluir")
        print("Nome alterado para: Dipirona Teste para excluir")
        time.sleep(1)

        print("\n9. Salvando edição...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#6C63FF\\]:nth-child(2)").click()
        print("Edição salva")
        time.sleep(2)

        print("\n10. Excluindo medicação...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-card:nth-child(6) "
                                 ".inline-flex:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#E74C3C\\]").click()
        print("Medicação excluída")
        time.sleep(2)

        print("\n11. Fazendo logout...")
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".text-\\[\\#E74C3C\\]").click()
        element = self.driver.find_element(By.CSS_SELECTOR,
                                           ".text-\\[\\#E74C3C\\]")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".bg-\\[\\#E74C3C\\]").click()
        print("Logout realizado")
        time.sleep(2)

        print("\n" + "=" * 60)
        print("TESTE CRUD DE MEDICAÇÕES CONCLUÍDO COM SUCESSO")
        print("=" * 60)
