# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDiariodeenxaquecaCRUDgatilho():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    self.driver.implicitly_wait(10)
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_diariodeenxaquecaCRUDgatilho(self):
    print("=" * 60)
    print("INICIANDO TESTE CRUD DE GATILHOS DE ENXAQUECA")
    print("=" * 60)

    print("\n1. Abrindo página inicial...")
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1184, 1040)
    print("Página inicial carregada")
    time.sleep(3)

    print("\n2. Fazendo login...")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("zenilda.vieira@uol.com.br")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
    print("Login realizado")
    time.sleep(3)

    print("\n3. Acessando seção de gatilhos...")
    self.driver.find_element(By.CSS_SELECTOR, ".rounded-md:nth-child(5)").click()
    print("Página de gatilhos acessada")
    time.sleep(2)

    print("\n4. Iniciando criação de novo gatilho...")
    self.driver.find_element(By.CSS_SELECTOR, ".hover\\3A bg-\\[\\#5850E6\\]").click()
    print("Formulário de criação de gatilho aberto")
    time.sleep(2)

    print("\n5. Preenchendo nome do gatilho...")
    self.driver.find_element(By.ID, "trigger-name").send_keys("Gatilho Teste")
    print("Nome preenchido: Gatilho Teste")
    time.sleep(1)

    print("\n6. Salvando gatilho...")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-\\[\\#6C63FF\\]:nth-child(2)").click()
    print("Gatilho salvo")
    time.sleep(2)

    print("\n7. Editando gatilho...")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-card:nth-child(6) .inline-flex:nth-child(1)").click()
    self.driver.find_element(By.ID, "trigger-name").send_keys("Gatilho Teste para excluir")
    self.driver.find_element(By.ID, "trigger-name").send_keys(Keys.ENTER)
    print("Nome alterado para: Gatilho Teste para excluir")
    time.sleep(1)

    print("\n8. Excluindo gatilho...")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-card:nth-child(6) .inline-flex:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-\\[\\#E74C3C\\]").click()
    print("Gatilho excluído")
    time.sleep(2)

    print("\n9. Fazendo logout...")
    self.driver.find_element(By.CSS_SELECTOR, ".text-\\[\\#E74C3C\\]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-\\[\\#E74C3C\\]").click()
    print("Logout realizado")
    time.sleep(2)

    print("\n" + "=" * 60)
    print("TESTE CRUD DE GATILHOS CONCLUÍDO COM SUCESSO")
    print("=" * 60)
  
